#define preinit

#include "BG21\preInitFunctions.sqf" //DO NOT REMOVE

LIB_GLOBAL_ENABLE_RADIO_IN_VEHICLE = false;
FOW_SYS_AMBIENTVOICES = false;
FOW_SYS_AMBIENTVOICES_PLAYER = false;
FOW_SYS_AMBIENTVOICES_DEATHSCREAMS = false;
